eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka-1:1111/eureka,http://eureka-2:1111/eureka
  instance:
    hostname: eureka-1 # cluster per1
    prefer-ip-address: true
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 100000 # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）