server:
  port: 8070

spring:
  profiles:
    active: dev
  application:
    name: sample-metrics

logging:
  file: ${spring.application.name}
  path: logs
  level:
     com:
       szzt:
        smart:
          framework: debug

endpoints:
  metrics:
    filter:
      enabled: false
metrics:
  enabled: true
  influxdb:
    host: 10.21.156.40
    port: 8086
  appName: ${spring.application.name}
  url-patterns:
              - /api/*
              - /kpi/*